version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # Primary port for all services
      - "4571:4571"  # S3 port
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"
